//! [`LlmProvider`] that drives `codex exec` as a completion engine.
//!
//! The process is ephemeral, runs away from the user's project, uses an
//! isolated minimal `CODEX_HOME`, and has a read-only sandbox. Codex's JSONL output currently
//! reports completed agent messages rather than token deltas, so each completed
//! message is forwarded to the sink as one chunk.

use std::pin::Pin;
use std::process::Stdio;

use tokio::io::{AsyncBufReadExt, AsyncReadExt, AsyncWriteExt, BufReader};
use tokio::process::Command;

use super::{CodeSink, CompletionRequest, LlmProvider, RawCompletion, Usage};

pub struct CodexCli;

const ENGINE_CONFIG: &str = r#"# Generated by sdkmode. This Codex instance is a text-completion
# engine, not an autonomous coding agent.
approval_policy = "never"
sandbox_mode = "read-only"
web_search = "disabled"

# Trim the request itself: replace Codex's coding-agent persona with
# sdkmode's contract, and drop the harness preamble sections. These keys are
# undocumented; a codex release that drops one ignores it silently, which
# degrades back to larger requests rather than breaking.
include_environment_context = false
include_permissions_instructions = false
include_apps_instructions = false
include_collaboration_mode_instructions = false

[features]
apps = false
artifact = false
auth_elicitation = false
browser_use = false
browser_use_external = false
browser_use_full_cdp_access = false
code_mode = false
code_mode_host = false
code_mode_only = false
computer_use = false
fast_mode = false
goals = false
hooks = false
image_generation = false
in_app_browser = false
memories = false
mentions_v2 = false
multi_agent = false
multi_agent_v2 = false
plugins = false
plugin_sharing = false
request_permissions_tool = false
shell_snapshot = false
shell_tool = false
skill_mcp_dependency_install = false
tool_call_mcp_elicitation = false
tool_suggest = false
unified_exec = false
unified_exec_zsh_fork = false
workspace_dependencies = false
"#;

/// The file inside the engine home that carries the request's system prompt.
/// Referenced from the generated config as `model_instructions_file`, which
/// replaces Codex's multi-thousand-token coding-agent persona outright.
const INSTRUCTIONS_FILE: &str = "instructions.md";

/// Encode a string as a TOML basic string. JSON string syntax is a subset of
/// TOML basic strings (same `\\`/`\"` escapes, `\uXXXX` for control
/// characters), so serde_json's encoder is a correct TOML encoder here.
fn toml_string(value: &str) -> String {
    serde_json::to_string(value).unwrap_or_else(|_| "\"\"".to_string())
}

/// Null out the model-catalog fields that force agent tools into every
/// request (`tool_mode = code_mode_only` alone injects ~3.4k tokens of
/// exec-cell and collaboration schemas, overriding the `[features]` table).
fn strip_agent_tools(catalog: &mut serde_json::Value) {
    let Some(models) = catalog.get_mut("models").and_then(|m| m.as_array_mut()) else {
        return;
    };
    for model in models {
        let Some(model) = model.as_object_mut() else {
            continue;
        };
        for field in ["tool_mode", "multi_agent_version", "apply_patch_tool_type"] {
            if model.contains_key(field) {
                model.insert(field.to_string(), serde_json::Value::Null);
            }
        }
    }
}

/// Rewrite Codex's cached model catalog with the agent-tool surfaces stripped
/// (see [`strip_agent_tools`]) and return the patched file's path. `None`
/// when no cache exists yet (the very first run) or it doesn't parse — the
/// override is skipped and that run pays the stock, larger request.
fn patched_model_catalog(engine_home: &std::path::Path) -> Option<std::path::PathBuf> {
    let cache = std::fs::read_to_string(engine_home.join("models_cache.json")).ok()?;
    let mut catalog: serde_json::Value = serde_json::from_str(&cache).ok()?;
    strip_agent_tools(&mut catalog);
    let path = engine_home.join("model_catalog.json");
    let models = catalog.get("models")?;
    std::fs::write(&path, serde_json::json!({ "models": models }).to_string()).ok()?;
    Some(path)
}

/// The full generated config: the file-path overrides (which vary per engine
/// home, and must precede the `[features]` table as top-level keys) followed
/// by [`ENGINE_CONFIG`].
fn engine_config(engine_home: &std::path::Path) -> String {
    let mut config = format!(
        "model_instructions_file = {}\n",
        toml_string(&engine_home.join(INSTRUCTIONS_FILE).to_string_lossy())
    );
    if let Some(catalog) = patched_model_catalog(engine_home) {
        config.push_str(&format!(
            "model_catalog_json = {}\n",
            toml_string(&catalog.to_string_lossy())
        ));
    }
    config.push_str(ENGINE_CONFIG);
    config
}

/// Build a separate Codex home containing only sdkmode's restrictive config.
/// Authentication remains owned by the user's normal Codex home and is linked
/// rather than copied, so refreshing or revoking login still has one source of
/// truth and sdkmode never duplicates credential contents.
fn engine_home() -> anyhow::Result<std::path::PathBuf> {
    let user_home = std::env::var_os("CODEX_HOME")
        .map(std::path::PathBuf::from)
        .or_else(|| {
            crate::snapshot::dirs_home().map(|mut home| {
                home.push(".codex");
                home
            })
        })
        .ok_or_else(|| anyhow::anyhow!("could not locate the user's Codex home"))?;
    let mut engine_home = crate::snapshot::dirs_home().unwrap_or_else(std::env::temp_dir);
    engine_home.push(".sdkmode");
    engine_home.push("codex-engine");
    std::fs::create_dir_all(&engine_home)?;
    std::fs::write(engine_home.join("config.toml"), engine_config(&engine_home))?;

    let source_auth = user_home.join("auth.json");
    let engine_auth = engine_home.join("auth.json");
    if !engine_auth.exists() {
        if !source_auth.exists() {
            anyhow::bail!(
                "Codex authentication was not found at {}; run `codex login` first",
                source_auth.display()
            );
        }
        #[cfg(unix)]
        std::os::unix::fs::symlink(&source_auth, &engine_auth)?;
        #[cfg(windows)]
        std::os::windows::fs::symlink_file(&source_auth, &engine_auth)?;
    }
    Ok(engine_home)
}

impl LlmProvider for CodexCli {
    fn complete<'a>(
        &'a self,
        request: &'a CompletionRequest<'a>,
        sink: &'a mut dyn CodeSink,
    ) -> Pin<Box<dyn Future<Output = anyhow::Result<RawCompletion>> + 'a>> {
        Box::pin(run_codex(request, sink))
    }
}

async fn run_codex(
    request: &CompletionRequest<'_>,
    sink: &mut dyn CodeSink,
) -> anyhow::Result<RawCompletion> {
    let engine_home = engine_home()?;
    // The system prompt rides as the model's instructions (via
    // `model_instructions_file` in the generated config), not inside the user
    // message: it replaces Codex's own persona instead of competing with it,
    // and it stays in the request's cacheable prefix.
    std::fs::write(engine_home.join(INSTRUCTIONS_FILE), request.system_prompt)?;
    let mut child = Command::new("codex")
        .arg("exec")
        .arg("--json")
        .arg("--ephemeral")
        .arg("--sandbox")
        .arg("read-only")
        .arg("--skip-git-repo-check")
        .arg("-")
        .env("CODEX_HOME", engine_home)
        // Keep project instructions and repository discovery out of this pure
        // completion request. Authentication still comes from CODEX_HOME.
        .current_dir(std::env::temp_dir())
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|error| {
            anyhow::anyhow!("failed to launch `codex` (is it installed and on PATH?): {error}")
        })?;

    {
        let mut stdin = child
            .stdin
            .take()
            .ok_or_else(|| anyhow::anyhow!("codex stdin was not captured"))?;
        // The contract already arrived as the model's instructions; the user
        // message is only the delimited program to complete.
        let prompt = format!(
            "The JavaScript session program to continue follows:\n<session>\n{}\n</session>",
            request.context
        );
        stdin.write_all(prompt.as_bytes()).await?;
        stdin.shutdown().await?;
    }

    let stderr = child
        .stderr
        .take()
        .ok_or_else(|| anyhow::anyhow!("codex stderr was not captured"))?;
    let stderr_task = tokio::spawn(async move {
        let mut buf = String::new();
        let _ = BufReader::new(stderr).read_to_string(&mut buf).await;
        buf
    });

    let stdout = child
        .stdout
        .take()
        .ok_or_else(|| anyhow::anyhow!("codex stdout was not captured"))?;
    let mut lines = BufReader::new(stdout).lines();
    let mut full = String::new();
    let mut usage = Usage::default();
    while let Some(line) = lines.next_line().await? {
        if let Some(text) = parse_agent_message(&line) {
            full.push_str(&text);
            sink.on_delta(&text);
        } else if let Some(turn_usage) = parse_turn_usage(&line) {
            usage = turn_usage;
        }
    }

    let status = child.wait().await?;
    let stderr = stderr_task.await.unwrap_or_default();
    if !status.success() {
        let diagnostics = stderr.trim();
        if diagnostics.is_empty() {
            anyhow::bail!(
                "`codex` exited with {status} but produced no diagnostics; check `codex --version`"
            );
        }
        anyhow::bail!("`codex` exited with {status}: {diagnostics}");
    }
    if full.is_empty() {
        anyhow::bail!("`codex` completed without an agent message");
    }

    Ok(RawCompletion { text: full, usage })
}

fn parse_turn_usage(line: &str) -> Option<Usage> {
    let value: serde_json::Value = serde_json::from_str(line).ok()?;
    if value.get("type")?.as_str()? != "turn.completed" {
        return None;
    }
    let usage = value.get("usage")?;
    Some(Usage {
        input_tokens: usage.get("input_tokens")?.as_u64()?,
        cached_input_tokens: usage
            .get("cached_input_tokens")
            .and_then(|value| value.as_u64())
            .unwrap_or(0),
        output_tokens: usage.get("output_tokens")?.as_u64()?,
        reasoning_output_tokens: usage
            .get("reasoning_output_tokens")
            .and_then(|value| value.as_u64())
            .unwrap_or(0),
        // `codex exec --json` does not expose a USD amount or the model needed
        // to calculate one correctly (and ChatGPT plans bill in credits).
        cost_usd: None,
    })
}

fn parse_agent_message(line: &str) -> Option<String> {
    let value: serde_json::Value = serde_json::from_str(line).ok()?;
    if value.get("type")?.as_str()? != "item.completed" {
        return None;
    }
    let item = value.get("item")?;
    if item.get("type")?.as_str()? != "agent_message" {
        return None;
    }
    Some(item.get("text")?.as_str()?.to_owned())
}

#[cfg(test)]
mod tests {
    use super::{
        ENGINE_CONFIG, engine_config, parse_agent_message, parse_turn_usage, strip_agent_tools,
        toml_string,
    };

    #[test]
    fn engine_config_disables_agent_surfaces() {
        for feature in [
            "apps",
            "browser_use",
            "computer_use",
            "goals",
            "hooks",
            "multi_agent",
            "plugins",
            "shell_tool",
            "unified_exec",
            "workspace_dependencies",
        ] {
            assert!(
                ENGINE_CONFIG.contains(&format!("{feature} = false")),
                "engine config did not disable {feature}"
            );
        }
        assert!(ENGINE_CONFIG.contains("web_search = \"disabled\""));
    }

    #[test]
    fn engine_config_trims_request_preamble() {
        for section in [
            "include_environment_context",
            "include_permissions_instructions",
            "include_apps_instructions",
            "include_collaboration_mode_instructions",
        ] {
            assert!(
                ENGINE_CONFIG.contains(&format!("{section} = false")),
                "engine config did not exclude {section}"
            );
        }
    }

    /// Top-level keys placed after a `[table]` header belong to that table in
    /// TOML, so the generated path keys must precede `[features]`.
    #[test]
    fn generated_config_puts_path_keys_before_the_features_table() {
        let config = engine_config(std::path::Path::new("/nonexistent/engine"));
        let instructions = config
            .find("model_instructions_file")
            .expect("config names the instructions file");
        let features = config.find("[features]").expect("config has features");
        assert!(instructions < features);
        assert!(config.contains("/nonexistent/engine"));
    }

    #[test]
    fn toml_string_escapes_quotes_and_backslashes() {
        assert_eq!(toml_string(r#"C:\engine "x""#), r#""C:\\engine \"x\"""#);
    }

    /// `tool_mode = "code_mode_only"` alone forces ~3.4k tokens of exec-cell
    /// and collaboration tool schemas into every request; the patched catalog
    /// must null every field that smuggles agent tools past `[features]`.
    #[test]
    fn strips_agent_tool_fields_from_every_model() {
        let mut catalog = serde_json::json!({
            "fetched_at": "now",
            "models": [
                {
                    "slug": "gpt-x",
                    "tool_mode": "code_mode_only",
                    "multi_agent_version": "v2",
                    "apply_patch_tool_type": "freeform",
                    "context_window": 372000,
                },
                { "slug": "gpt-y", "tool_mode": null },
            ],
        });
        strip_agent_tools(&mut catalog);
        let models = catalog["models"].as_array().unwrap();
        for model in models {
            assert!(model["tool_mode"].is_null(), "{model}");
        }
        assert!(models[0]["multi_agent_version"].is_null());
        assert!(models[0]["apply_patch_tool_type"].is_null());
        // Unrelated fields survive untouched.
        assert_eq!(models[0]["context_window"], 372000);
        // Fields a model never had are not invented.
        assert!(models[1].get("multi_agent_version").is_none());
    }

    #[test]
    fn parses_completed_agent_message() {
        let line = r#"{"type":"item.completed","item":{"id":"item_0","type":"agent_message","text":"return 42;"}}"#;
        assert_eq!(parse_agent_message(line).as_deref(), Some("return 42;"));
    }

    #[test]
    fn ignores_other_events() {
        let line = r#"{"type":"turn.completed","usage":{"input_tokens":12}}"#;
        assert_eq!(parse_agent_message(line), None);
    }

    #[test]
    fn parses_turn_token_usage() {
        let line = r#"{"type":"turn.completed","usage":{"input_tokens":32161,"cached_input_tokens":1920,"output_tokens":47,"reasoning_output_tokens":41}}"#;
        let usage = parse_turn_usage(line).unwrap();
        assert_eq!(usage.input_tokens, 32161);
        assert_eq!(usage.cached_input_tokens, 1920);
        assert_eq!(usage.output_tokens, 47);
        assert_eq!(usage.reasoning_output_tokens, 41);
        assert_eq!(usage.cost_usd, None);
    }
}
